version: "2.0"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
